// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTUBcpzOZF3N9JsnGOe6uZalDuqmekg4k',
    appId: '1:700044472543:web:2c8f322406d935f3c4396a',
    messagingSenderId: '700044472543',
    projectId: 'tiktok-clone-flutter-77995',
    authDomain: 'tiktok-clone-flutter-77995.firebaseapp.com',
    storageBucket: 'tiktok-clone-flutter-77995.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaDyLcmZRK9sDi0juVnXhjAmnfVTjAGfU',
    appId: '1:700044472543:android:ddd690122baddc48c4396a',
    messagingSenderId: '700044472543',
    projectId: 'tiktok-clone-flutter-77995',
    storageBucket: 'tiktok-clone-flutter-77995.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRcHOcXx0V5lJaFaaF0cAzNVGfwwr1O1A',
    appId: '1:700044472543:ios:6190f2a10d504c1ec4396a',
    messagingSenderId: '700044472543',
    projectId: 'tiktok-clone-flutter-77995',
    storageBucket: 'tiktok-clone-flutter-77995.appspot.com',
    androidClientId: '700044472543-jgtatnic9v91hk5depedpnmk5kilhpt5.apps.googleusercontent.com',
    iosClientId: '700044472543-d6uu2egmrl8o7the8m6fc72f5tgkfa4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRcHOcXx0V5lJaFaaF0cAzNVGfwwr1O1A',
    appId: '1:700044472543:ios:6190f2a10d504c1ec4396a',
    messagingSenderId: '700044472543',
    projectId: 'tiktok-clone-flutter-77995',
    storageBucket: 'tiktok-clone-flutter-77995.appspot.com',
    androidClientId: '700044472543-jgtatnic9v91hk5depedpnmk5kilhpt5.apps.googleusercontent.com',
    iosClientId: '700044472543-d6uu2egmrl8o7the8m6fc72f5tgkfa4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokCloneFlutter',
  );
}
